function [] = FullTimeZonePlot(SDNN_Pi,TT,tfind1,tfind2,tfind3,tfind4,tfind5,tfind6,tfind7,tfind8,tfind9,tfind10)
figure
plot(TT, SDNN_Pi, ...
     [tfind1;tfind1], [min(SDNN_Pi);max(SDNN_Pi)],"g-o", ...
     [tfind2;tfind2], [min(SDNN_Pi);max(SDNN_Pi)],"g-o", ...
     [tfind1;tfind2], [max(SDNN_Pi);max(SDNN_Pi)],"g-o",...
     [tfind1;tfind2], [min(SDNN_Pi);min(SDNN_Pi)],"g-o",...
     [tfind3;tfind3], [min(SDNN_Pi);max(SDNN_Pi)],"b-o", ...
     [tfind4;tfind4], [min(SDNN_Pi);max(SDNN_Pi)],"b-o", ...
     [tfind3;tfind4], [max(SDNN_Pi);max(SDNN_Pi)],"b-o",...
     [tfind3;tfind4], [min(SDNN_Pi);min(SDNN_Pi)],"b-o",...
     [tfind5;tfind5], [min(SDNN_Pi);max(SDNN_Pi)],"r-o", ...
     [tfind6;tfind6], [min(SDNN_Pi);max(SDNN_Pi)],"r-o", ...
     [tfind5;tfind6], [max(SDNN_Pi);max(SDNN_Pi)],"r-o",...
     [tfind5;tfind6], [min(SDNN_Pi);min(SDNN_Pi)],"r-o",...
     [tfind7;tfind7], [min(SDNN_Pi);max(SDNN_Pi)],"m-o", ...
     [tfind8;tfind8], [min(SDNN_Pi);max(SDNN_Pi)],"m-o", ...
     [tfind7;tfind8], [max(SDNN_Pi);max(SDNN_Pi)],"m-o",...
     [tfind7;tfind8], [min(SDNN_Pi);min(SDNN_Pi)],"m-o",...  
     [tfind9;tfind9], [min(SDNN_Pi);max(SDNN_Pi)],"k-o", ...
     [tfind10;tfind10], [min(SDNN_Pi);max(SDNN_Pi)],"k-o", ...
     [tfind9;tfind10], [max(SDNN_Pi);max(SDNN_Pi)],"k-o",...
     [tfind9;tfind10], [min(SDNN_Pi);min(SDNN_Pi)],"k-o")
end

